export const ITEMS = [
    // Armes
    { name: "Knife (1M)", 
        description: "+ 2 ATK", 
        emplacement: "1m",
        price: 10,
        buffHp: 0,
        buffAttack: 2,
        buffDefense: 0,
    },
    { name: "Hammer (1M)", 
        description: "+ 3 ATK", 
        emplacement: "1m",
        price: 15,
        buffHp: 0,
        buffAttack: 3,
        buffDefense: 0,
    },
    { name: "Big Hammer (2M)", 
        description: "+ 6 ATK", 
        emplacement: "2m",
        price: 45,
        buffHp: 0,
        buffAttack: 6,
        buffDefense: 0,
    },
    // Armure/PV
    { name: "Helmet", 
        description: "+ 12 maxHP", 
        emplacement: "head",
        price: 15,
        buffHp: 12,
        buffAttack: 0,
        buffDefense: 0,
    },
    { name: "Shield", 
        description: "+ 15 maxHP / + 5 DEF / + 1 ATK", 
        emplacement: "1m",
        price: 30,
        buffHp: 15,
        buffAttack: 1,
        buffDefense: 5,
    },
]

export const CONSOMMABLES = [
    // Potions
    { name: "Minor Health Potion", description: "Heal 20pv", price: 7 },
    { name: "Medium Health Potion", description: "Heal 40pv", price: 12 },
    // One-time Spells
    { name: "Exploooosion", description: "Deal 50% of attack to all annemies (and you if you have a 2M)", price: 10},
]